# ansible-playbook -K ./playbooks/new-pi.yml
---
- hosts: raspberrypi.kallan.xyz
  gather_facts: yes
  vars_prompt:
    - name: hostname
      prompt: "Please enter the hostname for your new Raspberry Pi"
      private: no

    - name: wifi_ssid
      prompt: "Enter SSID for WIFI"
      private: no

    - name: wifi_password
      prompt: "Enter Password for Wifi"
      private: no

    - name: raspberry_public_key
      prompt: "Enter path for public key"
      private: no

  vars:
    wifi_country: "AU"
    timezone: Australia/Perth

  become: true
  tasks:
    - import_tasks: ./playbooks/new-pi.yml
